file_format: "1"
id: corne
name: jagung42
type: shield
url: https://github.com
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - corne_left
  - corne_right
